import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Silkscreen } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { GradientBackdrop } from "@/components/ui/gradient-bg";
import { AuthProvider } from "@/contexts/auth-context";
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-playfair',
});

const silkscreen = Silkscreen({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-silkscreen',
});

export const metadata: Metadata = {
  title: "Luna AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silkscreen.variable} ${playfair.variable} antialiased h-full`}
        suppressHydrationWarning
      >
        {/* <GridPattern />  */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <div className="relative min-h-full">
            {/* <div className="fixed inset-0 -z-10">
              <GradientBackdrop />
            </div> */}
            <AuthProvider>
              {children}
              <Toaster position="top-center" richColors />
              <Analytics />
            </AuthProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
